name: Daily Simple Update
on:
  schedule:
    - cron: '0 22 * * *'  # 01:00 MSK
  workflow_dispatch:

jobs:
  daily-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        
      - name: Daily date update
        run: |
          MOSCOW_DATE=$(TZ=Europe/Moscow date +"%Y-%m-%d")
          MOSCOW_DATETIME="${MOSCOW_DATE}T01:00:00+03:00"
          
          # Обновить все HTML
          find . -name "*.html" -exec sed -i 's|content="202[0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+03:00"|content="'"$MOSCOW_DATETIME"'"|g' {} \;
          
          # Обновить JSON-LD
          find . -name "*.html" -exec sed -i 's|"dateModified": "202[0-9]-[0-9][0-9]-[0-9][0-9]"|"dateModified": "'"$MOSCOW_DATE"'"|g' {} \;
          
          # Sitemap
          [ -f sitemap.xml ] && sed -i 's|<lastmod>202[0-9]-[0-9][0-9]-[0-9][0-9]</lastmod>|<lastmod>'"$MOSCOW_DATE"'</lastmod>|g' sitemap.xml
          
          # Коммит
          git config --global user.email "daily@bot.com"
          git config --global user.name "Daily Bot"
          git add -A
          git commit -m "📅 $(TZ=Europe/Moscow date +'%Y-%m-%d %H:%M MSK')" || true
          git push || true
