name: Diagnose Issue
on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check repository permissions
        run: |
          echo "=== Repository Info ==="
          git remote -v
          git branch
          git status
          
          echo "=== GitHub Token Permissions ==="
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }} \
               | grep -E '"permissions"|"private"|"fork"'
          
          echo "=== Sample HTML file content ==="
          find . -name "*.html" -type f | head -1 | xargs head -20
