name: Simple Auto-Inject (Fixed)
on:
  workflow_dispatch:

jobs:
  inject:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Debug current state
        run: |
          echo "=== Текущее состояние ==="
          git status
          echo "=== Проверка HTML файлов ==="
          find . -name "*.html" -exec grep -l "article:modified_time" {} \; | head -5
          
      - name: Force inject auto-dates
        run: |
          MOSCOW_DATE=$(TZ=Europe/Moscow date +"%Y-%m-%d")
          MOSCOW_DATETIME="${MOSCOW_DATE}T01:00:00+03:00"
          
          echo "Принудительное обновление на дату: $MOSCOW_DATE"
          
          # Найти и обновить ВСЕ HTML файлы
          find . -name "*.html" -type f | while read file; do
              echo "Обновляем: $file"
              
              # Принудительно обновить ВСЕ даты на новые
              sed -i 's|content="2025-08-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]+03:00"|content="'"$MOSCOW_DATETIME"'"|g' "$file"
              sed -i 's|"dateModified": "2025-08-[0-9][0-9]"|"dateModified": "'"$MOSCOW_DATE"'"|g' "$file"
              sed -i 's|<lastmod>2025-08-[0-9][0-9]</lastmod>|<lastmod>'"$MOSCOW_DATE"'</lastmod>|g' "$file"
              
              # Добавить уникальный комментарий с временной меткой для гарантии изменений
              TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
              if ! grep -q "auto-inject-timestamp" "$file"; then
                  sed -i 's|</body>|<!-- auto-inject-timestamp: '"$TIMESTAMP"' -->\n</body>|' "$file"
              else
                  sed -i 's|<!-- auto-inject-timestamp: [^>]* -->|<!-- auto-inject-timestamp: '"$TIMESTAMP"' -->|' "$file"
              fi
          done
          
      - name: Add JavaScript to all pages
        run: |
          # Добавить JavaScript скрипт во все HTML файлы
          find . -name "*.html" -type f | while read file; do
              if ! grep -q "Moscow Auto-Update Script" "$file"; then
                  cat >> temp_script.txt << 'EOF'

<script>
// Moscow Auto-Update Script - Injected $(date)
(function() {
    const moscowTime = new Date().toLocaleString("en-US", {timeZone: "Europe/Moscow"});
    const moscowDate = new Date(moscowTime).toISOString().split('T')[0];
    const moscowDateTime = moscowDate + 'T01:00:00+03:00';
    
    // Update meta tag
    let metaModified = document.querySelector('meta[property="article:modified_time"]');
    if (!metaModified) {
        metaModified = document.createElement('meta');
        metaModified.setAttribute('property', 'article:modified_time');
        document.head.appendChild(metaModified);
    }
    metaModified.setAttribute('content', moscowDateTime);
    
    // Update JSON-LD
    document.querySelectorAll('script[type="application/ld+json"]').forEach(script => {
        try {
            const data = JSON.parse(script.textContent);
            if (data.dateModified) data.dateModified = moscowDate;
            script.textContent = JSON.stringify(data, null, 2);
        } catch(e) {}
    });
    
    console.log('Дата обновлена на:', moscowDateTime);
})();
</script>
EOF
                  
                  # Вставить скрипт перед </body>
                  sed -i 's|</body>|'"$(cat temp_script.txt | tr '\n' '§')"'</body>|' "$file"
                  sed -i 's/§/\n/g' "$file"
                  echo "JavaScript добавлен в: $file"
              fi
          done
          
          # Удалить временный файл
          rm -f temp_script.txt
          
      - name: Show changes
        run: |
          echo "=== Измененные файлы ==="
          git status --porcelain
          echo "=== Количество измененных файлов ==="
          git status --porcelain | wc -l
          
      - name: Commit with error handling
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Добавить все изменения
          git add -A
          
          # Проверить есть ли что коммитить
          if git diff --staged --quiet; then
              echo "❌ Нет изменений для коммита"
              echo "Принудительно создаем изменение..."
              echo "<!-- Force update: $(date) -->" >> README.md
              git add README.md
          fi
          
          # Коммит с обработкой ошибок
          MOSCOW_TIME=$(TZ=Europe/Moscow date +"%Y-%m-%d %H:%M MSK")
          if git commit -m "🤖 Принудительное обновление дат: $MOSCOW_TIME"; then
              echo "✅ Коммит создан успешно"
              
              # Push с повторными попытками
              for i in {1..3}; do
                  if git push; then
                      echo "✅ Push выполнен успешно"
                      break
                  else
                      echo "⚠️ Push failed, попытка $i из 3"
                      sleep 2
                  fi
              done
          else
              echo "❌ Ошибка при создании коммита"
              git status
              exit 1
          fi
