name: Full Update All Pages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  update-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update ALL HTML files
        run: |
          MOSCOW_DATE=$(TZ=Europe/Moscow date +"%Y-%m-%d")
          MOSCOW_DATETIME="${MOSCOW_DATE}T01:00:00+03:00"
          MOSCOW_TIME=$(TZ=Europe/Moscow date +"%Y-%m-%d %H:%M MSK")
          
          echo "Московская дата: $MOSCOW_DATE"
          echo "Московское время: $MOSCOW_DATETIME"
          
          find . -name "*.html" -type f | while read file; do
            echo "Обрабатываем: $file"
            
            if grep -q 'property="article:modified_time"' "$file"; then
              sed -i 's/property="article:modified_time" content="[^"]*"/property="article:modified_time" content="'"$MOSCOW_DATETIME"'"/g' "$file"
            else
              if grep -q '<meta name="viewport"' "$file"; then
                sed -i '/<meta name="viewport"/a \    <meta property="article:modified_time" content="'"$MOSCOW_DATETIME"'">' "$file"
              else
                sed -i '/<head>/a \    <meta property="article:modified_time" content="'"$MOSCOW_DATETIME"'">' "$file"
              fi
            fi
            
            if ! grep -q 'property="article:published_time"' "$file"; then
              sed -i '/<meta property="article:modified_time"/a \    <meta property="article:published_time" content="'"$MOSCOW_DATETIME"'">' "$file"
            fi
            
            if grep -q '"dateModified"' "$file"; then
              sed -i 's/"dateModified": "[^"]*"/"dateModified": "'"$MOSCOW_DATE"'"/g' "$file"
            fi
            
            if grep -q '"datePublished"' "$file"; then
              sed -i 's/"datePublished": "[^"]*"/"datePublished": "'"$MOSCOW_DATE"'"/g' "$file"
            fi
            
            UNIQUE_STAMP="auto-update-$(date +%s)"
            if grep -q 'auto-update-' "$file"; then
              sed -i 's/<!-- auto-update-[^>]* -->/<!-- '"$UNIQUE_STAMP"': '"$MOSCOW_TIME"' -->/g' "$file"
            else
              sed -i 's|</head>|    <!-- '"$UNIQUE_STAMP"': '"$MOSCOW_TIME"' -->\n</head>|' "$file"
            fi
          done
          
          echo "HTML файлов обработано: $(find . -name "*.html" -type f | wc -l)"
          
      - name: Create JavaScript file
        run: |
          cat > auto-dates.js << 'JSEOF'
          // Автообновление дат - Moscow Time
          (function() {
              var moscowTime = new Date().toLocaleString("en-US", {timeZone: "Europe/Moscow"});
              var moscowDate = new Date(moscowTime).toISOString().split('T')[0];
              var moscowDateTime = moscowDate + 'T01:00:00+03:00';
              
              var metaModified = document.querySelector('meta[property="article:modified_time"]');
              if (!metaModified) {
                  metaModified = document.createElement('meta');
                  metaModified.setAttribute('property', 'article:modified_time');
                  document.head.appendChild(metaModified);
              }
              metaModified.setAttribute('content', moscowDateTime);
              
              var metaPublished = document.querySelector('meta[property="article:published_time"]');
              if (!metaPublished) {
                  metaPublished = document.createElement('meta');
                  metaPublished.setAttribute('property', 'article:published_time');
                  metaPublished.setAttribute('content', moscowDateTime);
                  document.head.appendChild(metaPublished);
              }
              
              document.querySelectorAll('script[type="application/ld+json"]').forEach(function(script) {
                  try {
                      var data = JSON.parse(script.textContent);
                      var updated = false;
                      
                      if (data.dateModified) {
                          data.dateModified = moscowDate;
                          updated = true;
                      }
                      if (data.datePublished) {
                          data.datePublished = moscowDate;
                          updated = true;
                      }
                      
                      if (updated) {
                          script.textContent = JSON.stringify(data, null, 2);
                      }
                  } catch(e) {
                      console.log('JSON-LD update skipped');
                  }
              });
              
              if (!document.querySelector('.moscow-timestamp')) {
                  var timeEl = document.createElement('time');
                  timeEl.className = 'moscow-timestamp';
                  timeEl.setAttribute('datetime', moscowDateTime);
                  timeEl.setAttribute('itemprop', 'dateModified');
                  timeEl.style.display = 'none';
                  timeEl.textContent = 'Обновлено: ' + moscowDate;
                  document.body.appendChild(timeEl);
              }
          })();
          JSEOF
          
      - name: Add JavaScript to HTML files
        run: |
          find . -name "*.html" -type f | while read file; do
            if ! grep -q "Moscow Time" "$file"; then
              if grep -q "</body>" "$file"; then
                sed -i 's|</body>|<script>'"$(cat auto-dates.js)"'</script>\n</body>|' "$file"
                echo "JavaScript добавлен в: $file"
              fi
            else
              echo "JavaScript уже есть в: $file"
            fi
          done
          
          rm auto-dates.js
          
      - name: Update sitemap
        run: |
          MOSCOW_DATE=$(TZ=Europe/Moscow date +"%Y-%m-%d")
          
          if [ -f "sitemap.xml" ]; then
            sed -i 's/<lastmod>[^<]*<\/lastmod>/<lastmod>'"$MOSCOW_DATE"'<\/lastmod>/g' sitemap.xml
            echo "Sitemap обновлен"
          fi
          
      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          
          if git diff --staged --quiet; then
            echo "Принудительное обновление"
            FORCE_UPDATE=$(TZ=Europe/Moscow date +"%Y-%m-%d_%H-%M-%S")
            echo "<!-- Force: $FORCE_UPDATE -->" >> index.html
            git add index.html
          fi
          
          MOSCOW_TIME=$(TZ=Europe/Moscow date +"%Y-%m-%d %H:%M MSK")
          git commit -m "🤖 Обновление всех страниц: $MOSCOW_TIME"
          git push
          
          echo "ГОТОВО! Все страницы обновлены!"
