name: Full Update All Pages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # Каждый день в 01:00 MSK

jobs:
  update-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update ALL HTML files
        run: |
          # Московские дата и время
          MOSCOW_DATE=$(TZ=Europe/Moscow date +"%Y-%m-%d")
          MOSCOW_DATETIME="${MOSCOW_DATE}T01:00:00+03:00"
          MOSCOW_TIME=$(TZ=Europe/Moscow date +"%Y-%m-%d %H:%M MSK")
          
          echo "🗓️ Московская дата: $MOSCOW_DATE"
          echo "🕐 Московское время: $MOSCOW_DATETIME"
          
          # Счетчики
          TOTAL_FILES=0
          UPDATED_FILES=0
          
          # Найти ВСЕ HTML файлы
          echo "📂 Поиск HTML файлов..."
          find . -name "*.html" -type f | while read file; do
            echo "📄 Обрабатываем: $file"
            TOTAL_FILES=$((TOTAL_FILES + 1))
            
            # 1. Обновить/добавить article:modified_time
            if grep -q 'property="article:modified_time"' "$file"; then
              # Обновить существующий
              sed -i 's/property="article:modified_time" content="[^"]*"/property="article:modified_time" content="'"$MOSCOW_DATETIME"'"/g' "$file"
              echo "  ✏️ Обновлен modified_time"
            else
              # Добавить новый после viewport или в head
              if grep -q '<meta name="viewport"' "$file"; then
                sed -i '/<meta name="viewport"/a \    <meta property="article:modified_time" content="'"$MOSCOW_DATETIME"'">' "$file"
              else
                sed -i '/<head>/a \    <meta property="article:modified_time" content="'"$MOSCOW_DATETIME"'">' "$file"
              fi
              echo "  ➕ Добавлен modified_time"
            fi
            
            # 2. Добавить/обновить article:published_time
            if ! grep -q 'property="article:published_time"' "$file"; then
              sed -i '/<meta property="article:modified_time"/a \    <meta property="article:published_time" content="'"$MOSCOW_DATETIME"'">' "$file"
              echo "  ➕ Добавлен published_time"
            fi
            
            # 3. Обновить JSON-LD Schema dateModified
            if grep -q '"dateModified"' "$file"; then
              sed -i 's/"dateModified": "[^"]*"/"dateModified": "'"$MOSCOW_DATE"'"/g' "$file"
              echo "  🔄 Обновлен JSON-LD dateModified"
            fi
            
            # 4. Обновить JSON-LD Schema datePublished на сегодняшнюю дату
            if grep -q '"datePublished"' "$file"; then
              sed -i 's/"datePublished": "[^"]*"/"datePublished": "'"$MOSCOW_DATE"'"/g' "$file"
              echo "  🔄 Обновлен JSON-LD datePublished"
            fi
            
            # 5. Добавить временную метку для гарантии изменений
            UNIQUE_STAMP="auto-update-$(date +%s)"
            if grep -q 'auto-update-' "$file"; then
              sed -i 's/<!-- auto-update-[^>]* -->/<!-- '"$UNIQUE_STAMP"': '"$MOSCOW_TIME"' -->/g' "$file"
            else
              sed -i 's|</head>|    <!-- '"$UNIQUE_STAMP"': '"$MOSCOW_TIME"' -->\n</head>|' "$file"
            fi
            echo "  ⏰ Добавлена временная метка"
            
            UPDATED_FILES=$((UPDATED_FILES + 1))
          done
          
          echo "📊 Найдено HTML файлов: $(find . -name "*.html" -type f | wc -l)"
          
      - name: Add JavaScript auto-update to all pages
        run: |
          # JavaScript код для автообновления
          cat > /tmp/auto-script.js << 'EOF'

<script>
// Автообновление дат - Moscow Time Injected
(function() {
    'use strict';
    
    // Московское время
    const moscowTime = new Date().toLocaleString("en-US", {timeZone: "Europe/Moscow"});
    const moscowDate = new Date(moscowTime).toISOString().split('T')[0];
    const moscowDateTime = moscowDate + 'T01:00:00+03:00';
    
    console.log('🕐 Обновление дат на московское время:', moscowDateTime);
    
    // Обновить article:modified_time
    let metaModified = document.querySelector('meta[property="article:modified_time"]');
    if (!metaModified) {
        metaModified = document.createElement('meta');
        metaModified.setAttribute('property', 'article:modified_time');
        document.head.appendChild(metaModified);
    }
    metaModified.setAttribute('content', moscowDateTime);
    
    // Обновить article:published_time
    let metaPublished = document.querySelector('meta[property="article:published_time"]');
    if (!metaPublished) {
        metaPublished = document.createElement('meta');
        metaPublished.setAttribute('property', 'article:published_time');
        metaPublished.setAttribute('content', moscowDateTime);
        document.head.appendChild(metaPublished);
    }
    
    // Обновить все JSON-LD Schema
    document.querySelectorAll('script[type="application/ld+json"]').forEach(function(script) {
        try {
            const data = JSON.parse(script.textContent);
            let updated = false;
            
            if (data.dateModified) {
                data.dateModified = moscowDate;
                updated = true;
            }
            if (data.datePublished) {
                data.datePublished = moscowDate;
                updated = true;
            }
            
            if (updated) {
                script.textContent = JSON.stringify(data, null, 2);
            }
        } catch(e) {
            console.log('JSON-LD update skipped');
        }
    });
    
    // Добавить скрытую SEO-метку
    if (!document.querySelector('.moscow-timestamp')) {
        const timeEl = document.createElement('time');
        timeEl.className = 'moscow-timestamp';
        timeEl.setAttribute('datetime', moscowDateTime);
        timeEl.setAttribute('itemprop', 'dateModified');
        timeEl.style.display = 'none';
        timeEl.textContent = 'Обновлено: ' + moscowDate;
        document.body.appendChild(timeEl);
    }
    
})();
</script>
EOF
          
          # Добавить скрипт во ВСЕ HTML файлы
          find . -name "*.html" -type f | while read file; do
            # Проверить, есть ли уже наш скрипт
            if ! grep -q "Moscow Time Injected" "$file"; then
              # Добавить перед </body> если он есть
              if grep -q "</body>" "$file"; then
                # Читаем скрипт и добавляем
                sed -i 's|</body>|'"$(cat /tmp/auto-script.js | tr '\n' '§')"'\n</body>|' "$file"
                # Заменяем обратно переносы строк
                sed -i 's/§/\n/g' "$file"
                echo "✅ JavaScript добавлен в: $file"
              else
                echo "⚠️ Нет </body> в файле: $file"
              fi
            else
              echo "⏭️ JavaScript уже есть в: $file"
            fi
          done
          
          # Удалить временный файл
          rm -f /tmp/auto-script.js
          
      - name: Update sitemap.xml
        run: |
          MOSCOW_DATE=$(TZ=Europe/Moscow date +"%Y-%m-%d")
          
          if [ -f "sitemap.xml" ]; then
            echo "📍 Обновляем sitemap.xml..."
            # Обновить все lastmod на текущую дату
            sed -i 's/<lastmod>[^<]*<\/lastmod>/<lastmod>'"$MOSCOW_DATE"'<\/lastmod>/g' sitemap.xml
            
            # Добавить changefreq если нет
            sed -i '/<lastmod>/a \    <changefreq>daily</changefreq>' sitemap.xml
            
            echo "✅ Sitemap обновлен на дату: $MOSCOW_DATE"
          else
            echo "❌ Файл sitemap.xml не найден"
          fi
          
      - name: Commit and push all changes
        run: |
          # Настройка Git
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Добавить все изменения
          git add -A
          
          # Показать статистику изменений
          echo "📊 Статистика изменений:"
          git status --porcelain | wc -l | xargs echo "Файлов изменено:"
          
          # Проверить есть ли что коммитить
          if git diff --staged --quiet; then
            echo "⚠️ Нет изменений - создаем принудительное обновление"
            # Принудительно создать изменение
            FORCE_UPDATE=$(TZ=Europe/Moscow date +"%Y-%m-%d_%H-%M-%S")
            echo "<!-- Force update: $FORCE_UPDATE -->" >> index.html
            git add index.html
          fi
          
          # Создать коммит
          MOSCOW_TIME=$(TZ=Europe/Moscow date +"%Y-%m-%d %H:%M MSK")
          if git commit -m "🤖 Полное обновление всех страниц: $MOSCOW_TIME"; then
            echo "✅ Коммит создан успешно"
            
            # Push с несколькими попытками
            for i in {1..3}; do
              if git push; then
                echo "🚀 Push выполнен успешно с попытки $i"
                break
              else
                echo "⚠️ Push неудачен, попытка $i из 3"
                sleep 2
              fi
              
              if [ $i -eq 3 ]; then
                echo "❌ Все попытки push исчерпаны"
                exit 1
              fi
            done
          else
            echo "❌ Ошибка создания коммита"
            exit 1
          fi
          
          echo "🎉 ГОТОВО! Все HTML страницы обновлены с московским временем!"
