name: Test Manual Update
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        
      - name: Simple test update
        run: |
          MOSCOW_DATE=$(TZ=Europe/Moscow date +"%Y-%m-%d")
          MOSCOW_TIME=$(TZ=Europe/Moscow date +"%Y-%m-%d %H:%M MSK")
          
          echo "Тестируем обновление на: $MOSCOW_DATE"
          
          # Простое обновление одного файла
          if [ -f "index.html" ]; then
            sed -i 's/<meta property="article:modified_time" content="[^"]*"/<meta property="article:modified_time" content="'"$MOSCOW_DATE"'T01:00:00+03:00"/g' index.html
            echo "<!-- Test update: $MOSCOW_TIME -->" >> index.html
          fi
          
          # Коммит
          git config --global user.email "test@example.com"
          git config --global user.name "Test Bot"
          git add -A
          git commit -m "🧪 Тест обновления: $MOSCOW_TIME"
          git push
