name: Working Auto Dates
on:
  schedule:
    - cron: '0 22 * * *'  # Каждый день в 01:00 MSK (22:00 UTC)
  workflow_dispatch:  # Ручной запуск

jobs:
  update-dates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update dates in all files
        run: |
          # Московская дата и время
          MOSCOW_DATE=$(TZ=Europe/Moscow date +"%Y-%m-%d")
          MOSCOW_DATETIME="${MOSCOW_DATE}T01:00:00+03:00"
          TIMESTAMP=$(TZ=Europe/Moscow date +"%Y-%m-%d_%H-%M-%S")
          
          echo "🕐 Обновление на московскую дату: $MOSCOW_DATE"
          echo "⏰ Московское время: $MOSCOW_DATETIME"
          
          # Счетчик файлов
          FILES_UPDATED=0
          
          # 1. Обновить все HTML файлы
          find . -name "*.html" -type f | while read file; do
            echo "📄 Обрабатываем: $file"
            
            # Обновить существующие meta-теги или добавить новые
            if grep -q 'article:modified_time' "$file"; then
              sed -i 's/<meta property="article:modified_time" content="[^"]*"/<meta property="article:modified_time" content="'"$MOSCOW_DATETIME"'"/g' "$file"
            else
              # Добавить после viewport если его нет
              if grep -q '<meta name="viewport"' "$file"; then
                sed -i '/<meta name="viewport"/a \    <meta property="article:modified_time" content="'"$MOSCOW_DATETIME"'">' "$file"
              else
                # Добавить в head
                sed -i '/<head>/a \    <meta property="article:modified_time" content="'"$MOSCOW_DATETIME"'">' "$file"
              fi
            fi
            
            # Добавить published_time если нет
            if ! grep -q 'article:published_time' "$file"; then
              sed -i '/<meta property="article:modified_time"/a \    <meta property="article:published_time" content="'"$MOSCOW_DATETIME"'">' "$file"
            fi
            
            # Обновить JSON-LD Schema
            sed -i 's/"dateModified": "[^"]*"/"dateModified": "'"$MOSCOW_DATE"'"/g' "$file"
            sed -i 's/"datePublished": "2025-08-[0-9][0-9]"/"datePublished": "'"$MOSCOW_DATE"'"/g' "$file"
            
            # Добавить уникальный комментарий для гарантии изменений
            sed -i 's/<!-- auto-update: [^>]* -->/<!-- auto-update: '"$TIMESTAMP"' -->/g' "$file"
            if ! grep -q 'auto-update:' "$file"; then
              sed -i 's|</head>|    <!-- auto-update: '"$TIMESTAMP"' -->\n</head>|' "$file"
            fi
            
            FILES_UPDATED=$((FILES_UPDATED + 1))
          done
          
          # 2. Обновить sitemap.xml
          if [ -f "sitemap.xml" ]; then
            sed -i 's/<lastmod>[^<]*<\/lastmod>/<lastmod>'"$MOSCOW_DATE"'<\/lastmod>/g' sitemap.xml
            echo "✅ Sitemap обновлен"
          fi
          
          echo "📊 Обработано файлов: $FILES_UPDATED"
          
      - name: Add JavaScript auto-update script
        run: |
          # JavaScript код для автообновления
          cat > auto-update-script.html << 'EOF'

<script>
// Auto-update dates - Moscow timezone
(function() {
    'use strict';
    
    // Получить московское время
    const moscowTime = new Date().toLocaleString("en-US", {timeZone: "Europe/Moscow"});
    const moscowDate = new Date(moscowTime).toISOString().split('T')[0];
    const moscowDateTime = moscowDate + 'T01:00:00+03:00';
    
    // Обновить article:modified_time
    let metaModified = document.querySelector('meta[property="article:modified_time"]');
    if (!metaModified) {
        metaModified = document.createElement('meta');
        metaModified.setAttribute('property', 'article:modified_time');
        document.head.appendChild(metaModified);
    }
    metaModified.setAttribute('content', moscowDateTime);
    
    // Обновить article:published_time
    let metaPublished = document.querySelector('meta[property="article:published_time"]');
    if (!metaPublished) {
        metaPublished = document.createElement('meta');
        metaPublished.setAttribute('property', 'article:published_time');
        metaPublished.setAttribute('content', moscowDateTime);
        document.head.appendChild(metaPublished);
    }
    
    // Обновить JSON-LD Schema
    document.querySelectorAll('script[type="application/ld+json"]').forEach(function(script) {
        try {
            const data = JSON.parse(script.textContent);
            if (data.dateModified) {
                data.dateModified = moscowDate;
            }
            if (data.datePublished && !data.originalDatePublished) {
                data.originalDatePublished = data.datePublished;
                data.datePublished = moscowDate;
            }
            script.textContent = JSON.stringify(data, null, 2);
        } catch(e) {
            console.log('Schema update skipped');
        }
    });
    
    // Добавить скрытую временную метку для SEO
    if (!document.querySelector('.seo-timestamp')) {
        const timeEl = document.createElement('time');
        timeEl.className = 'seo-timestamp';
        timeEl.setAttribute('datetime', moscowDateTime);
        timeEl.setAttribute('itemprop', 'dateModified');
        timeEl.style.display = 'none';
        timeEl.textContent = moscowDate;
        document.body.appendChild(timeEl);
    }
    
})();
</script>
EOF
          
          # Добавить скрипт во все HTML файлы
          find . -name "*.html" -type f | while read file; do
            # Проверить, есть ли уже скрипт
            if ! grep -q "Auto-update dates - Moscow timezone" "$file"; then
              # Добавить перед </body>
              if grep -q "</body>" "$file"; then
                sed -i 's|</body>|'"$(cat auto-update-script.html | tr '\n' '§')"'\n</body>|' "$file"
                sed -i 's/§/\n/g' "$file"
                echo "✅ JavaScript добавлен в: $file"
              fi
            fi
          done
          
          # Удалить временный файл
          rm auto-update-script.html
          
      - name: Commit and push changes
        run: |
          # Настройка Git
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Добавить все изменения
          git add -A
          
          # Проверить есть ли изменения
          if git diff --staged --quiet; then
            echo "ℹ️ Нет изменений - принудительно создаем"
            # Принудительно создать изменение
            FORCE_TIMESTAMP=$(TZ=Europe/Moscow date +"%Y-%m-%d %H:%M:%S MSK")
            echo "<!-- Force update: $FORCE_TIMESTAMP -->" >> index.html
            git add index.html
          fi
          
          # Создать коммит
          MOSCOW_TIME=$(TZ=Europe/Moscow date +"%Y-%m-%d %H:%M MSK")
          git commit -m "🤖 Авто-обновление дат: $MOSCOW_TIME" || echo "Commit failed, continuing..."
          
          # Push с повторными попытками
          for i in {1..5}; do
            if git push origin main; then
              echo "✅ Push успешен с попытки $i"
              break
            elif git push origin master; then
              echo "✅ Push успешен в master с попытки $i"  
              break
            else
              echo "⚠️ Push неудачен, попытка $i из 5"
              sleep 3
            fi
            
            if [ $i -eq 5 ]; then
              echo "❌ Все попытки push исчерпаны"
              exit 1
            fi
          done
          
          echo "🎉 Обновление дат завершено успешно!"
